spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务

--- #################### 接口文档配置 ####################
springdoc:
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui.html
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

knife4j:
  enable: true # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn


#  jackson:
#    serialization:
#      write-dates-as-timestamps: true # 设置LocalDateTime格式，使用时间戳
#      write-date-timestamps-as-nanoseconds: false # 设置不使用nanoseconds。例如说 1611460870.401，而是直接 1611460870401
#      write-durations-as-timestamps: true # 设置Duration的格式，使用时间戳
#      fail-on-empty-beans: false # 允许序列化无属性的Bean
#


--- #################### 芋道相关配置 ####################
gmall:
  security:
    mock-enabled: true
  swagger:
    author: zhengpanone
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: 1.0.0


