--- #################### 接口文档配置 ####################
springdoc:
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui.html
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

--- #################### 数据库相关配置 ####################
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/gmall_bpm?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&createDatabaseIfNotExist=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave: # 模拟从库，可根据自己需要修改
          lazy: true # 开启懒加载，保证启动速度
          url: jdbc:mysql://127.0.0.1:3306/gmall_bpm_slave?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&createDatabaseIfNotExist=true
          username: root
          password: root

  # flyway
  flyway:
    locations: classpath:db/migration # 迁移脚本的位置
    baseline-on-migrate: true # 在没有元数据表的情况下，针对非空Schema执行迁移时是否自动调用基线
    enabled: true
    sql-migration-prefix: V
    sql-migration-suffixes: .sql


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
  mapper-locations: classpath*:/mapper/**Mapper.xml

# 工作流 Flowable 配置
flowable:
  check-process-definitions: true #是否需要自动部署流程定义 /resources/processes 自动部署 BPMN XML 流程。
  cmmn:
    async:
      executor:
        async-job-lock-time-in-millis: 300000 #异步作业在被异步执行器取走后的锁定时间（以毫秒计）。在这段时间内，其它异步执行器不会尝试获取及锁定这个任务。'
        default-async-job-acquire-wait-time-in-millis: 10000 #异步作业获取线程在进行下次获取查询前的等待时间（以毫秒计）。只在当次没有取到新的异步作业，或者只取到很少的异步作业时生效。默认值= 10秒。'
        default-queue-size-full-wait-time-in-millis: 0 #异步作业（包括定时器作业与异步执行）获取线程在队列满时，等待执行下次查询的等待时间（以毫秒计）。默认值为0（以向后兼容）'
        default-timer-job-acquire-wait-time-in-millis: 1000 #定时器作业获取线程在进行下次获取查询前的等待时间（以毫秒计）。只在当次没有取到新的定时器作业，或者只取到很少的定时器作业时生效。默认值= 10秒。'
        max-async-jobs-due-per-acquisition: 1 # （译者补）单次查询的异步作业数量。默认值为1，以降低乐观锁异常的可能性。除非你知道自己在做什么，否则请不要修改这个值。'
        retry-wait-time-in-millis: 500 #（译者补不了了）'
        timer-lock-time-in-millis: 300000 #定时器作业在被异步执行器取走后的锁定时间（以毫秒计）。在这段时间内，其它异步执行器不会尝试获取及锁定这个任务。'
    async-executor-activate: true # 是否启用异步执行器。
    deploy-resources: true #是否部署资源。默认值为''true''。
    deployment-name: SpringBootAutoDeployment #CMMN资源部署的名字。
    enable-safe-xml: true # 在解析CMMN XML文件时进行额外检查。参见 https://www.flowable.org/docs/userguide/index.html#advanced.safe.bpmn.xml # 不幸的是，部分平台（JDK 6，JBoss）上无法使用这个功能，因此如果你所用的平台在XML解析时不支持StaxSource，需要禁用这个功能。'
    enabled: false # 是否启用CMMN引擎。'
    resource-location: classpath*:/cases/ # CMMN资源的路径。'
    resource-suffixes: # **.cmmn,**.cmmn11,**.cmmn.xml,**.cmmn11.xml # 需要扫描的资源后缀名。'
    servlet:
      load-on-startup: -1 # 启动时加载CMMN servlet。'
      name: Flowable CMMN Rest API # CMMN servlet的名字。'
      path: /cmmn-api # CMMN servlet的context path。'
  content:
    enabled: false # 是否启动Content引擎。'
    servlet:
      load-on-startup: -1 # 启动时加载Content servlet。'
      name: Flowable Content Rest API # Content servlet的名字。'
      path: /content-api # Content servlet的context path。'
    storage:
      create-root: true # 如果根路径不存在，是否需要创建？'
      root-folder: # 存储content文件（如上传的任务附件，或表单文件）的根路径。'
  custom-mybatis-mappers: # 需要添加至引擎的自定义Mybatis映射的FQN。'
  custom-mybatis-x-m-l-mappers: # 需要添加至引擎的自定义Mybatis XML映射的路径。'
  database-schema: # 如果数据库返回的元数据不正确，可以在这里设置schema用于检测/生成表。'


  # 1. false: 默认值，Flowable 启动时，对比数据库表中保存的版本，如果不匹配。将抛出异常
  # 2. true: 启动时会对数据库中所有表进行更新操作，如果表存在，不做处理，反之，自动创建表
  # 3. create_drop: 启动时自动创建表，关闭时自动删除表
  # 4. drop_create: 启动时，删除旧表，再创建新表
  database-schema-update: true # 设置为 false，可通过 https://github.com/flowable/flowable-sql 初始化
  db-history-used: true # flowable6 默认 true 生成信息表，无需手动设置
  deployment-name: SpringBootAutoDeployment # 自动部署的名称。'
  dmn:
    deploy-resources: true # 是否部署资源。默认为''true''。'
    deployment-name: SpringBootAutoDeployment # DMN资源部署的名字。'
    enable-safe-xml: true # 在解析DMN XML文件时进行额外检查。参见 https://www.flowable.org/docs/userguide/index.html#advanced.safe.bpmn.xml。不幸的是，部分平台（JDK 6，JBoss）上无法使用这个功能，因此如果你所用的平台在XML解析时不支持StaxSource，需要禁用这个功能。'
    enabled: false # 是否启用DMN引擎。'
    history-enabled: false # 是否启用DMN引擎的历史。'
    resource-location: classpath*:/dmn/ # DMN资源的路径。'
    resource-suffixes: # **.dmn,**.dmn.xml,**.dmn11,**.dmn11.xml # 需要扫描的资源后缀名。'
    servlet:
      load-on-startup: -1 # 启动时加载DMN servlet。'
      name: Flowable DMN Rest API # DMN servlet的名字。'
      path: /dmn-api # DMN servlet的context path。'
    strict-mode: true # 如果希望避免抉择表命中策略检查导致失败，可以将本参数设置为false。如果检查发现了错误，会直接返回错误前一刻的中间结果。'
  form:
    deploy-resources: true # 是否部署资源。默认为''true''。'
    deployment-name: SpringBootAutoDeployment # Form资源部署的名字。'
    enabled: false # 是否启用Form引擎。'
    resource-location: classpath*:/forms/ # Form资源的路径。'
    resource-suffixes: # **.form # 需要扫描的资源后缀名。'
    servlet:
      load-on-startup: -1 # 启动时加载Form servlet。'
      name: Flowable Form Rest API # Form servlet的名字。'
      path: /form-api # Form servlet的context path。'
  history-level: audit # full：保存历史数据的最高级别，可保存全部流程相关细节，包括流程流转各节点参数
  idm:
    enabled: false # 是否启用IDM引擎。'
    ldap:
      attribute:
        email: # 用户email的属性名。'
        first-name: # 用户名字的属性名。'
        group-id: # 用户组ID的属性名。'
        group-name: # 用户组名的属性名。'
        group-type: # 用户组类型的属性名。'
        last-name: # 用户姓的属性名。'
        user-id: # 用户ID的属性名。'
      base-dn: # 查找用户与组的DN（标志名称 distinguished name）。'
      cache:
        group-size: -1 # 设置{@link org.flowable.ldap.LDAPGroupCache}的大小。这是LRU缓存，用于缓存用户及组，以避免每次都查询LDAP系统。'
      enabled: false # 是否启用LDAP IDM 服务。'
      group-base-dn: # 组查找的DN。'
      initial-context-factory: com.sun.jndi.ldap.LdapCtxFactory # 初始化上下文工厂的类名。'
      password: # 连接LDAP系统的密码。'
      port: -1 # LDAP系统的端口。'
      query:
        all-groups: # 查询所有组所用的语句。'
        all-users: # 查询所有用户所用的语句。'
        groups-for-user: # 按照指定用户查询所属组所用的语句'
        user-by-full-name-like: # 按照给定全名查找用户所用的语句。'
        user-by-id: # 按照userId查找用户所用的语句。'
      search-time-limit: 0 # 查询LDAP的超时时间（以毫秒计）。默认值为''0''，即“一直等待”。'
      security-authentication: simple # 连接LDAP系统所用的''java.naming.security.authentication''参数的值。'
      server: # LDAP系统的主机名。如''ldap://localhost''。'
      user: # 连接LDAP系统的用户ID。'
      user-base-dn: # 查找用户的DN。'
    password-encoder: # 使用的密码编码类型。'
    servlet:
      load-on-startup: -1 # 启动时加载IDM servlet。'
      name: Flowable IDM Rest API # IDM servlet的名字。'
      path: /idm-api # IDM servlet的context path。'
  mail:
    server:
      default-from: flowable@localhost # 发送邮件时使用的默认发信人地址。'
      host: localhost # 邮件服务器。'
      password: # 邮件服务器的登录密码。'
      port: 1025 # 邮件服务器的端口号。'
      use-ssl: false # 是否使用SSL/TLS加密SMTP传输连接（即SMTPS/POPS)。'
      use-tls: false # 使用或禁用STARTTLS加密。'
      username: # 邮件服务器的登录用户名。如果为空，则不需要登录。'
  process:
    async:
      executor:
        async-job-lock-time-in-millis: 300000 # 异步作业在被异步执行器取走后的锁定时间（以毫秒计）。在这段时间内，其它异步执行器不会尝试获取及锁定这个任务。'
        default-async-job-acquire-wait-time-in-millis: 10000 # 异步作业获取线程在进行下次获取查询前的等待时间（以毫秒计）。只在当次没有取到新的异步作业，或者只取到很少的异步作业时生效。默认值= 10秒。'
        default-queue-size-full-wait-time-in-millis: 0 # 异步作业（包括定时器作业与异步执行）获取线程在队列满时，等待执行下次查询的等待时间（以毫秒计）。默认值为0（以向后兼容）'
        default-timer-job-acquire-wait-time-in-millis: 10000 # 定时器作业获取线程在进行下次获取查询前的等待时间（以毫秒计）。只在当次没有取到新的定时器作业，或者只取到很少的定时器作业时生效。默认值= 10秒。'
        max-async-jobs-due-per-acquisition: 1 # （译者补）单次查询的异步作业数量。默认值为1，以降低乐观锁异常的可能性。除非你知道自己在做什么，否则请不要修改这个值。'
        retry-wait-time-in-millis: 500 # ???（译者补不了了）'
        timer-lock-time-in-millis: 300000 # 定时器作业在被异步执行器取走后的锁定时间（以毫秒计）。在这段时间内，其它异步执行器不会尝试获取及锁定这个任务。'
    async-executor-activate: true # 是否启用异步执行器。'
    definition-cache-limit: -1 # 流程定义缓存中保存流程定义的最大数量。默认值为-1（缓存所有流程定义）。'
    enable-safe-xml: true # 在解析BPMN XML文件时进行额外检查。参见 https://www.flowable.org/docs/userguide/index.html#advanced.safe.bpmn.xml。不幸的是，部分平台（JDK 6，JBoss）上无法使用这个功能，因此如果你所用的平台在XML解析时不支持StaxSource，需要禁用这个功能。'
    servlet:
      load-on-startup: -1 # 启动时加载Process servlet。'
      name: Flowable BPMN Rest API # Process servlet的名字。'
      path: /process-api # Process servelet的context path。'
  process-definition-location-prefix: classpath*:/processes/ # 自动部署时查找流程的目录。'
  process-definition-location-suffixes: # **.bpmn20.xml,**.bpmn # ''processDefinitionLocationPrefix''路径下需要部署的文件的后缀（扩展名）。'


--- #################### gmall相关配置 ####################
gmall:
  web:
    admin-ui:
      url: http://dashboard.gmall.cn