version: '3'
services:
  gmall-gateway:
    image: gmall-gateway
    container_name: gmall-gateway
    environment:
      - TZ=Asia/Shanghai

    volumes:
      - /docker/gmall-cloud/logs:/root/logs/
    restart: always
    network_mode: host # 以主机网络环境运行

  gmall-coupon:
    image: zhengpanone/jdk8:latest
    container_name: gmall-coupon
    ports:
      - "9010:9010"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
      # command:  -java -Xms512M -Xmx512M  -jar -Duser.timezone=GMT+08 /testProject/testProject-1.0.0.jar --spring.config.location=/testProject/config/application.yml
      # https://blog.aymar.cn/post/docker-compose-tong-shi-chuang-jian-duo-ge-shu-ju-ku/


