### 创建用户
POST {{sysBaseUrl}}/admin-api/user/create
Content-Type: application/json

{
    "password": "admin123",
    "nickname": "管理员",
    "email": "admin@qq.com",
    "phone": "13800138000",
    "status": 1,
    "remark": "管理员"
}


### 创建角色
POST {{sysBaseUrl}}/admin-api/role/create
Content-Type: application/json

{
  "name": "管理员",
  "code": "admin",
  "status": 1,
  "remark": "管理员"
}

### 删除角色
POST {{sysBaseUrl}}/admin-api/role/delete
Content-Type: application/json

{
  "id": []
}

### 创建字典
POST {{sysBaseUrl}}/admin-api/dict/create
Content-Type: application/json

###

