
### 普通对话
GET http://localhost:48085/ai/chat/simple?
    prompt="你好，请问你叫什么名字？"

### 多轮对话
GET http://localhost:48085/ai/chat/chatHistory?
    prompt="它的优点呢？"

### 流式对话
GET http://localhost:48085/ai/chat/stream?
    prompt="你好，请问你叫什么名字？"