spring:
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
#      base-url: @ai.dashscope.base-url@
      chat:
        options:
          model: qwen3.5-plus
          temperature: 0.7

logging:
  level:
    org.springframework.web.client: DEBUG
    com.alibaba.cloud.ai: DEBUG

--- #################### gmall相关配置 ####################
gmall:
  web:
    admin-ui:
      url: http://dashboard.gmall.cn