spring:
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml # 加载【本地】配置
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml # 加载【Nacos】的配置

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gmall_gateway?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto

  bus:
    enabled: true
    destination: springCloudBus # 自定义广播消息的 exchange 名称（默认就是 springCloudBus）

  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          lower-case-service-id: true
      routes:
        ## system-server 服务
        - id: system-admin-api
          uri: lb://system-server
          predicates:
            - Path=/admin-api/system/**
          filters:
            - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs

        - id: system-app-api
          uri: lb://system-server
          predicates:
            - Path=/app-api/system/**
          filters:
            - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs

        # infra-server 服务
#        - id: infra-admin-api
#          uri: lb://infra-server
#          predicates:
#            - Path=/admin-api/infra/**
#          filters:
#            - RewritePath=/admin-api/infra/v3/api-docs, /v3/api-docs

        ## bpm-server 服务
#        - id: bpm-admin-api
#          uri: lb://bpm-server
#          predicates:
#            - Path=/admin-api/bpm/**
#          filters:
#            - RewritePath=/admin-api/bpm/v3/api-docs, /v3/api-docs
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/system 前缀



--- #################### 接口文档配置 ####################
springdoc:
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui.html
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档



